-- =============================================================================
-- VigaBSS 5.0 — Rollback 151: Remove soft-delete columns
-- =============================================================================
-- Reverses migration 151.
-- =============================================================================

ALTER TABLE users DROP INDEX idx_users_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE clients DROP INDEX idx_clients_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE contacts DROP INDEX idx_contacts_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE organizations DROP INDEX idx_organizations_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE organization_users DROP INDEX idx_organization_users_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE sites DROP INDEX idx_sites_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE plans DROP INDEX idx_plans_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE plan_addons DROP INDEX idx_plan_addons_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE contracts DROP INDEX idx_contracts_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE contract_addons DROP INDEX idx_contract_addons_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE devices DROP INDEX idx_devices_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE tickets DROP INDEX idx_tickets_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE ticket_comments DROP INDEX idx_ticket_comments_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE invoices DROP INDEX idx_invoices_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE invoice_items DROP INDEX idx_invoice_items_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE payments DROP INDEX idx_payments_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE payment_allocations DROP INDEX idx_payment_allocations_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE credit_notes DROP INDEX idx_credit_notes_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE credit_note_items DROP INDEX idx_credit_note_items_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE expenses DROP INDEX idx_expenses_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE quotes DROP INDEX idx_quotes_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE quote_items DROP INDEX idx_quote_items_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE tax_rates DROP INDEX idx_tax_rates_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE tax_rules DROP INDEX idx_tax_rules_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE payment_gateways DROP INDEX idx_payment_gateways_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE recurring_payment_profiles DROP INDEX idx_recurring_payment_profiles_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE nas DROP INDEX idx_nas_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE radius DROP INDEX idx_radius_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE ip_pools DROP INDEX idx_ip_pools_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE ip_assignments DROP INDEX idx_ip_assignments_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE network_links DROP INDEX idx_network_links_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE vlans DROP INDEX idx_vlans_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE outages DROP INDEX idx_outages_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE snmp_profiles DROP INDEX idx_snmp_profiles_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE snmp_profile_oids DROP INDEX idx_snmp_profile_oids_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE speed_tests DROP INDEX idx_speed_tests_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE device_config_backups DROP INDEX idx_device_config_backups_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE firerelay_nodes DROP INDEX idx_firerelay_nodes_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE firerelay_client_routing DROP INDEX idx_firerelay_client_routing_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE service_areas DROP INDEX idx_service_areas_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE coverage_zones DROP INDEX idx_coverage_zones_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE warehouses DROP INDEX idx_warehouses_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE inventory_items DROP INDEX idx_inventory_items_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE inventory_stock DROP INDEX idx_inventory_stock_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE files DROP INDEX idx_files_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE notifications DROP INDEX idx_notifications_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE message_templates DROP INDEX idx_message_templates_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE promotions DROP INDEX idx_promotions_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE sla_definitions DROP INDEX idx_sla_definitions_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE suspension_rules DROP INDEX idx_suspension_rules_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE api_tokens DROP INDEX idx_api_tokens_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE roles DROP INDEX idx_roles_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE webhooks DROP INDEX idx_webhooks_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE alert_rules DROP INDEX idx_alert_rules_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE client_mx_profiles DROP INDEX idx_client_mx_profiles_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE organization_mx_profiles DROP INDEX idx_organization_mx_profiles_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE contract_templates_mx DROP INDEX idx_contract_templates_mx_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE concession_titles DROP INDEX idx_concession_titles_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE regulatory_filings DROP INDEX idx_regulatory_filings_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE ift_statistical_reports DROP INDEX idx_ift_statistical_reports_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE csd_certificates DROP INDEX idx_csd_certificates_deleted_at, DROP COLUMN deleted_at;
ALTER TABLE pac_providers DROP INDEX idx_pac_providers_deleted_at, DROP COLUMN deleted_at;
